---
title: "D2SC ICMA notebook"
output: html_notebook
author: "Madison Chin"
date: "`r Sys.Date()`"
---

#ICMA Sept 9 2024
```{r}
#The downloaded binary packages are in
#C:\Users\mchin\AppData\Local\Temp\RtmpW0fCpq\downloaded_packages
plot(cars)
```
#ICMA Sept 11 2024
```{r}
ohno_this_is_a_nightmare <- "hello"
```
```{r}
2+2
```
```{r}
x <- 2+2

```

```{r}
?mean
#how we can look for things we don't know.(use ?)
#function call looks like mean()
#arrays look like c(2,3,4)
```

```{r}
sd(1:2) ^ 2
```
#ICMA Sept 16 2024

```{r}
#make sure to complete first code chunks 
# to create a vector, use c(list, numbers, inside, like, this)
my_numbers <- c( 1,2,3,4,5,8,9,10)
```

```{r}
library(magrittr)
library(tidyverse)
#must be loaded each session
```

```{r}
mean(my_numbers)
```
```{r}
my_numbers %>% 
  mean()
```
```{r}
getwd()
```

```{r}
?mtcars
mtcars

```

```{r}
write_csv(mtcars, # object name, 
         "mtcars_fromR.csv" #file name to save it"
         )
#utils is BaseR, but we want to use the _ version, as it is a part of the tidyverse pkg.
#is wihout rowname implementation and use of "rowtoname function"
```


 
```{r}
read_csv("mtcars_fromR.csv")

```
#ICMA Sept 18 2024

```{r}
?ChickWeight
glimpse(ChickWeight)
```
```{r}

ChickWeight %>%
  select(Chick,weight) %>%
  head (n= 3)
```

```{r}
#adding a new column called weight lbs
ChickWeight %>%
  mutate(weight_lbs = weight/453.6) %>%
#mutate always adds the columns to the end of your graphs
#create summary table that has, #of chicks, avg weight,avg lbs on Day 20.
  #for getting each diet group, we can use (the below) 
 group_by(Diet,Time)%>%
  summarise(N= n(), mean_wgt_gm = mean(weight),
            mean_wgt_lbs = mean(weight_lbs)) %>%
            filter(Time == 20)
```
```{r}
glimpse(mtcars)
```
#ICMA Sept 23 2024 
```{r}
head(billboard)
?pivot_longer
```
```{r}
billboard_long <- billboard %>%
pivot_longer(cols = starts_with("wk"),
             names_to = "week",
             values_to = "position",
             names_prefix = "wk", 
             values_drop_na = TRUE)
```

```{r}
head(billboard_long)
dim(billboard)
dim(billboard_long)
#look! _long is actually longer! with more rows
```

```{r}
billboard_long
```
```{r}
billboard_long%>%
  pivot_wider(names_from = week,
              values_from = position)
#error bc we did not add a column name
```

```{r}
#separate () separates a column by a specific separator
?separate
billboard %>%
  separate(col = date.entered, 
           into = c("year", "month", "day"))
#separated the dates into year, month, day
#she automatically set the sep(separator) to be an non-alphanumeric characters

```

```{r}
#billboard%>%
#unite(data,col, sep "_" )
```
```{r}
#explicit missing values - NA is in the data-set
#implicit missing - the value just DOES not appear in the data-set (you have to know this data)
#complete() - turns implicit missing values into explicit missing values 
#fill()- fills missing values in selected columns using the next or previous entry. 
#replace_NA() - Replace NA's with specified values  -> 0 instead of NA.
#NA_if : Convert specified values to NA. 
```

#ICMA Sept 25 2024

```{r}
head =(ChickWeight)
ChickWeight %>%
  ggplot(aes(x = weight)) + #provide the aes(aesthetic mapping, in this case, x-axis only)
geom_histogram()
```
```{r}
head =(ChickWeight)
ChickWeight %>%
  ggplot(aes(y = weight, 
             x = Time,
             color = Diet)) + 
  geom_point() +
  geom_smooth() +
#creates function of best fit
# to remove the error bands, write the following = geom_smooth(se = FALSE)
theme_minimal()
```
#ICMA October 7 2024

```{r}
as.numeric("12")
#only parses digits, words do not count, but numbers as chars work tho.
```

We can use is.numeric -> aka is.TYPE() in order to do a check to see i she is wo she is. 
Doubles are r's default type of numeric.
"as.integer()" forces a type to become an integer.
To check type, we can do typeof(), to get the type directly.

```{r}
as.integer(12.3)
```

True = 1 
False = 0

TRY on your own activity
```{r}
3 < 5 | FALSE
#true
```
```{r}
is.numeric(mean(c(12,31,15.57,4)))
#true 2nd
```

```{r}
((1+2)< -1000) | (TRUE | NA)
```
