---
title: "R Notebook"
output: html_notebook
---

 

```{r set-up}
library(tidyverse)
library(ggdist)
knitr::opts_chunk$set(echo = FALSE,root.dir = '~/GitHub/ADV-Topics-2---DSR-w-R/Data Exercise/DE3')

```

```{r read_data}

desc <- read_csv('data/desc_all.csv')
e2_err <- read_csv('data/e2_error_df.csv') 
e5_err<- read_csv('data/e5_error_df.csv')
e15_err<- read_csv('data/e15_error_df.csv')

```

```{r}
desc%>%
  ggplot(aes(y = no_categories))+
  geom_histogram(binwidth = 1,
                 color = "white", 
                 fill = "black")

```
```{r}
desc%>%
  ggplot(aes(y = no_categories))+#because we are creating a histogram
  geom_histogram() + 
  facet_grid(~group_name)

```
We noticed that there is an NA category, so we should make sure that those are "missing" values and not just the letters are "NA". 

```{r}
desc%>%
  distinct(group_name)
```
We also noticed that there seems to be a larger sample (i.e, mroe overall counts) for the english mono an dnon-asian-multi groups. Let's see if that tis tru adn what the sample sizes are. 

```{r}
desc%>%
  count(group_name) #this is counting the number of rows.
```

## Plot number 1 

```{r}
desc%>%
  filter(is.na(group_name) == FALSE)%>%
  mutate(full_group_name = case_when(group_name == "south_asian" ~ "South Asian",
                                     group_name == "se_asian" ~ "Southeast Asian",
                                     group_name == "non_asian_multi" ~ "Non-Asian Multilingual",
                                     group_name == "eng_mono" ~ "English monolingual diverse",
                                     group_name == "east_asian" ~ "East Asian"),
         full_group_name = factor(full_group_name, 
                                  levels = rev(c("English monolingual diverse",
                                             "Non-Asian Multilingual",
                                             "South Asian",
                                             "Southeast Asian",
                                             "East Asian"))))%>%
  ggplot(aes(y = full_group_name,
             x = no_categories,
             fill = full_group_name,
             fct_rev(full_group_name)
            )) + 
  geom_boxplot( color = "black") + 
  xlim(0,15) + 
  labs(x = "Number of Categories", 
       y = "Group Name",
       title = "Average Number of Categories Created per group") + 
  theme_minimal()+
  theme(legend.position = "none") + 
  scale_fill_viridis_d(option = "plasma")
  
  #we need to re-order the categories using "factor".

#annotate (geom = "text", y= 1, x = 17.5, ) .... sd was calculated in an earlier chunk. *

```
#11/25/24 Continuing with DE3

```{r}
e2_err
e15_err
e5_err

```
```{r}
err_data <- bind_rows(e2_err, e5_err)%>%
  bind_rows(e15_err)

```

```{r}
err_data%>%
  ggplot(aes(x = error_2_df, y = error_type,color = group ))+
  stat_summary(fun.data = mean_se, geom = "pointrange", position = position_dodge(0.7)) #dodge meaning right next to each other 
#had to rename the blank column in the data to "error_type" manually



```
```{r}
theme_set()
```


```{r}
#commented out notes from continuation point
#graph is incorrect due to missing where/what error_type represents, will fix after class

```


